FROM node as react-build
WORKDIR /app
COPY . .
RUN yarn
RUN yarn build 


FROM golang:latest as go-builder
ENV CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 \
    GO111MODULE=on
WORKDIR /app
COPY . /app
RUN go build api/cmd/main.go 


FROM alpine
WORKDIR /app
EXPOSE 8080
COPY --from=react-build  /app/build ./build
COPY --from=go-builder /app/main  .
CMD /app/main
